### ISSUE TITLE
拖放资源时报错

### ISSUE THREAD

**Issue by nicejintian** [wzpan/rhubarb-lip-sync-ccc#1]
问题:
![微信图片_20201217172250](https://user-images.githubusercontent.com/15918889/102468511-8ff92100-408c-11eb-9ed9-421e3a65e4a2.png)

2020-12-17T09:11:55.742Z - error: ReferenceError: cc is not defined
    at HTMLElement._isTypeValid (D:\install\CocosDashboard_1.0.6\resources\.editors\Creator\2.4.3\resources\app.asar\editor\page\ui\elements\asset.js:1:4085)
    at D:\install\CocosDashboard_1.0.6\resources\.editors\Creator\2.4.3\resources\app.asar\editor\page\ui\elements\asset.js:1:4737
    at EventEmitter.<anonymous> (D:\install\CocosDashboard_1.0.6\resources\.editors\Creator\2.4.3\resources\app.asar\editor-framework\lib\renderer\ipc.js:1:3788)
    at EventEmitter.emit (events.js:194:13)

解决方法:
https://forum.cocos.org/t/2-20-native-asset/90209

![微信图片_20201217172156](https://user-images.githubusercontent.com/15918889/102468400-6dff9e80-408c-11eb-8304-da20e358c80e.png)

**Comment by wzpan** [comment]
收到，我晚点试试2.2.0的兼容性

**Comment by wzpan** [comment]
@nicejintian 我在 Mac 下的 2.4.3 版本未能复现。请问是不是 windows 下照着你这么改后就可以正常使用了呢？

**Comment by nicejintian** [comment]
是的,我用的creator 2.4.3,刚发现问题时,我在论坛查了一下,说是 在插件的 package.json 加一下 "engineSupport": true&nbsp;就可以了, 然后尝试了一下,的确可行. 还有一个问题, 就是生成 animationClip 后,必须重新打开creator,才能在creator动画编辑器内看到关键帧,应该是保存animationClip&nbsp;内容之后没有刷新吧.不过不影响使用.👍👍👍




------------------ 原始邮件 ------------------
发件人: "潘伟洲"<notifications@github.com&gt;; 
发送时间: 2020年12月18日(星期五) 凌晨0:07
收件人: "wzpan/rhubarb-lip-sync-ccc"<rhubarb-lip-sync-ccc@noreply.github.com&gt;; 
抄送: "WLAN"<2670813470@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [wzpan/rhubarb-lip-sync-ccc] 拖放资源时报错 (#1)





 
@nicejintian 我在 Mac 下的 2.4.3 版本未能复现。请问是不是 windows 下照着你这么改后就可以正常使用了呢？

**Comment by wzpan** [comment]
> 还有一个问题, 就是生成 animationClip 后,必须重新打开creator,才能在creator动画编辑器内看到关键帧

是的。这个问题我有在 README 里说明。

> Tips: if you find the ouput animation clip contains no frames, try restarting Cocos Creator and it should work.

**Comment by wzpan** [comment]
已添加该字段并提审v0.0.2版本。感谢！
